[package]
name = "markdown"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
pulldown-cmark = "0.10"
ribir = { path = "../../ribir", features = ["material", "widgets"] }
syntect = { version = "5.3", default-features = false, features = ["default-fancy"] }
webbrowser = "1.0.5"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp"] }
parking_lot = "0.12"
once_cell = "1.20"
tokio = { version = "1.0", features = ["time"] }
rfd = "0.14"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
wasm-bindgen.workspace = true

[dev-dependencies]
ribir = { path = "../../ribir", features = ["material", "widgets", "test-utils"] }

[features]
wgpu = ["ribir/wgpu"]
debug = ["ribir/debug"]

[[bin]]
name = "markdown"
path = "src/main.rs"

[package.metadata.bundle]
product-name = "Markdown Editor"
identifier = "com.ribir.markdown-editor"
icon = ["../../examples/Logo.ico"]
targets = "all"
